name: CI

on:
  push:
    paths-ignore:
      - docs/**
      - cmake/**
      - .vscode/**
      - README.md

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        target: [win32, x64, arm64]
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: true
          # Fetch all to make git describe work correctly
          fetch-depth: 0

      - name: Setup CMake
        run: cmake -B build -A ${{matrix.target}} -D Binding_Java=ON

      - name: Build
        run: cmake --build build --config Release --target ALL_BUILD && tree build/java /A /F

      - name: Pack
        run: cmake --build build --config Release --target package && tree build/pack /A /F

      - name: Rename and Prepare Artifacts
        shell: pwsh
        run: |
          mkdir dist
          
          $arch = "${{ matrix.target }}"
          $targetName = ""
          if ($arch -eq "x64") { $targetName = "IngameIME_Java-x64.dll" }
          elseif ($arch -eq "win32") { $targetName = "IngameIME_Java-x86.dll" }
          elseif ($arch -eq "arm64") { $targetName = "IngameIME_Java-arm64.dll" }
          
          $dllFile = Get-ChildItem -Path build -Filter "*.dll" -Recurse | Select-Object -First 1
          if ($dllFile) {
           Copy-Item $dllFile.FullName "dist/$targetName"
           echo "Successfully prepared $targetName"
          } else {
           throw "Could not find compiled DLL file!"
          }

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: IngameIME-Native-${{ matrix.target }}
          path: dist/

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
         generate_release_notes: true

         # Publish Packed files
         files: build/pack/*.zip,build/pack/*.sha1
         fail_on_unmatched_files: true
